### ISSUE TITLE
Adafruit Git hub 

### ISSUE THREAD

**Issue by Jimcodom** [adafruit/Basic-Chat#2]
https://learn.adafruit.com/crack-the-code/overview

I'm getting a build error trying to use the sample code for BLE , apparently it needs to be updated to swift 4. Any chance there is a swift 4 version so I can continue learning how to create an iphone app for my Bluetooth Arduino devices>

**Comment by ladyada** [comment]
no ETA! you can use Swift 3 for now

**Comment by Jimcodom** [comment]
Ok, but then not sure what I need to do different to get it to compile with latest Xcode , seems like the build would give me a warning not just stop.  I followed your instructions became a registered developer, (great instructional as I would never have figured it on my own) paid $100 and hoped to use your example to get me started. But given it won't build I am at a loss. Any help you could provide me would be greatly appreciated. @ladyada

**Comment by Jimcodom** [comment]
@ladyada

**Comment by ladyada** [comment]
hiya, we have no other code examples - this is the only code right now and it is Swift 3 at this time. we have no ETA on a Swift 4 version. Apple likes to do this to their developers for some reason :(

**Comment by Jimcodom** [comment]
Ok, thanks again....😎


Jim Odom
Mobile: 772-321-4158
