### ISSUE TITLE
My peripheral is not found

### ISSUE THREAD

**Issue by nolispe280** [adafruit/Basic-Chat#3]
Hi! Thanks for the Basic-Chat app. It looks like it's exactly what I would need for my project. Unfortunately, it does not find my BLE module. It's an SH-HC-08 connected to an arduino. I communicate with it fine with LightBlue but not with your app. Have you ever encountered that before?

**Comment by ladyada** [comment]
we dont know or support that module. it must work with the nordic uart protocol. adafruit bluefruit works for sure!
