### ISSUE TITLE
Problem running on ios13

### ISSUE THREAD

**Issue by glingle05** [adafruit/Basic-Chat#9]
I get the following crash when trying this on iOS 13 when trying to use with
Bluefruit LE B9D3:
`
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /.../Developer/AdaFruit-Basic-Chat/Basic Chat/BLECentralViewController.swift, line 259
2019-09-26 19:17:29.303876-0700 Basic Chat[327:17526] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /.../Developer/AdaFruit-Basic-Chat/Basic Chat/BLECentralViewController.swift, line 259
`

This code was used as a template for our application and we're experiencing
the same issue.  The real problem seems to be that the error argument is populated and not checked.  The error.localizedDescription is "Reading is not permitted."

I have tested connecting to my BlueFruit with the LE Connect app - worked just fine.  I can send request string and get expected data stream (lines of temperture data) back.

Testing was done on a brand new iPad Mini running latest iOS 13.1.
I had to add new required bluetooth purpose string, NSBluetoothAlwaysUsageDescription in info.plist. 

Any help / updates appreciated.
Thanks!
Glenn

**Comment by glingle05** [comment]
Further info:
Testing was done on a brand new iPad Mini

**Comment by glingle05** [comment]
Actually just added 
```
        if error != nil {
            print("Got error \(error!.localizedDescription)")
            return
        }
```
above the if and it started working

**Comment by tannewt** [comment]
Sounds like you figured it out! Is adding NSBluetoothAlwaysUsageDescription to the info.plist all that is needed?

**Comment by glingle05** [comment]
It was the ignoring of the error (see code above) - that avoided accessing the characteristic.value that avoided a crash.  Later it seems the read permission was acquired, and I started getting data.
The new description was another side-issue.

**Comment by glingle05** [comment]
feel free to close this jira.

**Comment by mcritz** [comment]
@glingle05 Should be fixed in master.
